name: Deploy backend

on:
  push:
    branches:
      - develop
      - release

jobs:
  deploy-dev:
    name: Deploy to DEV
    if: github.ref_name == 'develop'
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
            nvm use 22
            cd ~/megatest
            git pull origin develop
            npm ci
            systemctl restart megatest

  deploy-prod:
    name: Deploy to PROD
    if: github.ref_name == 'release'
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
            nvm use 22
            cd ~/megaback
            git pull origin release
            npm ci
            systemctl restart megaback
