name: Deploy to PROD

on:
  push:
    branches:
      - release

jobs:
  deploy:
    uses: ./.github/workflows/deploy-backend.yml
    with:
      branch: 'release'
      server-path: '~/megaback'
      service-name: 'megaback'
    secrets:
      HOST: ${{ secrets.HOST }}
      USER: ${{ secrets.USER }}
      SSH_KEY: ${{ secrets.SSH_KEY }}
