name: Deploy backend

on:
  push:
    branches:
      - develop
      - release

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name == 'release' && 'prod' || 'dev' }}

    steps:
      - name: Deploy backend via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            if [ "${{ github.ref_name }}" = "release" ]; then
              cd ~/megaback
              git pull origin release
              systemctl restart megaback
            else
              cd ~/megatest
              git pull origin develop
              systemctl restart megatest
            fi
